/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS_B.view;

import UAS_B.controller.PinjamanController;
import javax.swing.JComboBox;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Hp
 */
public class FormPinjaman extends javax.swing.JFrame {

    /**
     * Creates new form FormPinjaman
     */
    PinjamanController controller;
    public FormPinjaman() {
        initComponents();
        controller = new PinjamanController(this);
        controller.bersihForm();
        controller.tampilData();
        controller.setCboKodeNasabah();

    }

    public JTable getTblPinjaman() {
        return tblPinjaman;
    }

    public javax.swing.JTextField getTxtTanggalPinjaman(){
       return txtTanggalPinjaman;
    }
    public javax.swing.JTextField getTxtLamaPinjaman(){
        return txtLamaPinjaman;
    } 
    public javax.swing.JTextField getTxtJumlahPinjaman(){
        return txtJumlahPinjaman;
    } 


    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnInsert() {
        return btnInsert;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JComboBox<String> getCboKodeNasabah() {
        return cboKodeNasabah;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboKodeNasabah = new javax.swing.JComboBox<>();
        txtTanggalPinjaman = new javax.swing.JTextField();
        txtJumlahPinjaman = new javax.swing.JTextField();
        txtLamaPinjaman = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPinjaman = new javax.swing.JTable();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pinjaman");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Form Pinjaman");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 0, 140, 14);

        jLabel2.setText("Kode Nasabah");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 90, 14);

        jLabel4.setText("Tanggal Pinjaman");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 60, 100, 14);

        jLabel5.setText("Jumlah Pinjaman");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 80, 14);

        jLabel6.setText("Lama Pinjaman");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 80, 14);

        cboKodeNasabah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboKodeNasabah);
        cboKodeNasabah.setBounds(130, 20, 540, 20);

        txtTanggalPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalPinjamanActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggalPinjaman);
        txtTanggalPinjaman.setBounds(130, 50, 530, 30);

        txtJumlahPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahPinjamanActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahPinjaman);
        txtJumlahPinjaman.setBounds(130, 90, 530, 30);
        getContentPane().add(txtLamaPinjaman);
        txtLamaPinjaman.setBounds(130, 130, 530, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(130, 220, 61, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(220, 220, 67, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(310, 220, 63, 23);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(400, 220, 70, 23);

        tblPinjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Nasabah", "Tanggal Pinjaman", "Jumlah Pinjaman", "Lama Pinjaman", "Bunga Pinjaman", "Angsuran Pokok", "Angsuran Perbulan", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPinjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPinjaman);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 670, 100);

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(510, 220, 65, 23);

        setSize(new java.awt.Dimension(707, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTanggalPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalPinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalPinjamanActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        controller.savePinjaman();
        controller.tampilData();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       controller.deletePinjaman();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        controller.updatePinjaman();
        controller.tampilData();
        controller.bersihForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        controller.bersihForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tblPinjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamanMouseClicked
        controller.getPinjaman();
    }//GEN-LAST:event_tblPinjamanMouseClicked

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtJumlahPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPinjamanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormPinjaman().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboKodeNasabah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPinjaman;
    private javax.swing.JTextField txtJumlahPinjaman;
    private javax.swing.JTextField txtLamaPinjaman;
    private javax.swing.JTextField txtTanggalPinjaman;
    // End of variables declaration//GEN-END:variables

    
}
